language: python
python:
- 3.6.2
install:
- pip install -r requirements.txt
script:
- "./manage.py test"
# notifications:
#   slack:
#     secure: RvrL97QLY1bOQd7VoQ6XQKsoRbz+02bSWtPVfBNJZ4QUUZ1AXegAdH5pQnIoE4C8ldwaEP6cjMItJ4HpkFDs8dcPVwUDxcM9EFunFQwLoKQ3VdxTSgcAp2+tNBluzynlmANLWnjennuA3Z4r+e47XWOKnmMhjfBiycnecb2f2Wi04fZ5GT+QM9PD6We+OISrjH8nZf9lwsCy9mFAyRQyIULMA+GhAr878zj4C0J0DSLA4Jq9Rk4TvjZgE9TCu5gxYVrOGZK9h6tWEeQm36yRho6+aZFVI45au2iwlfNbOkViFqB0Ijtq6LpINWgLVN1+FOglZuRjHpeK0aUExVKABnBNQHYo5Gs3ZaI83nh9G3UvBC+5XGW56W+XcUSPXVMiNPireDaWJ2z9C5uJ/elGNG/UrgkhccLOrxR/3YG9dGSwCWe2eLdfN2ZhBhVLcFDuStynNe5SwVoqBP9kOpqiYQe5VUFgqThlwxyqlhuj1lqktQEiWP3Cncci7KMVDqJjNIdS2/7f3UlcF7Hszm8djddJpAO2X89fN1kKBL2sN1Tr5t1QQwOQQLY36UMp2CbLXtodXY8IafpJaTkzfBBLQdFb+0JdcGYBvbS4R2SoaHjDEKOQ2q17yiqposAgr2gGYFMp0sMXQGGRgg1GF7BLF3pADVJAj/D/aOi6l5HAtOM=
