# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-17 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_merchantprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MerchantProfile',
            new_name='Profile',
        ),
    ]
