# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-21 23:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_emailactivation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='shop',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='merchant',
            new_name='is_merchant',
        ),
    ]
